# Generated by Django 5.2.4 on 2025-07-19 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('phone_number', models.CharField(max_length=15)),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('approved_limit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('current_debt', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='loan',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='monthly_repayment',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='loan',
            name='monthly_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterModelTable(
            name='loan',
            table=None,
        ),
        migrations.AlterField(
            model_name='loan',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.customer'),
        ),
    ]
