

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: credit_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/credit_system
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app

  celery:
    build: .
    command: celery -A credit_system worker --loglevel=info
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/credit_system
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app

volumes:
  postgres_data:
